[env]
GDAL_HOME= "C:/Users/sales/vcpkg/installed/x64-windows"
GDAL_INCLUDE_DIR = "C:/Users/sales/vcpkg/installed/x64-windows/include"
GDAL_LIB_DIR = "C:/Users/sales/vcpkg/installed/x64-windows/lib"
PROJ_DATA = "C:/Users/sales/vcpkg/installed/x64-windows/share/proj"
PROJ_LIB = "C:/Users/sales/vcpkg/installed/x64-windows"
PKG_CONFIG_PATH =  "C:/Users/sales/vcpkg/installed/x64-windows/lib/pkgconfig"
